const sofas = [
  {
    id: "AGORA",
    nombre: "ÁGORA",
    img: "../assets/imgs/SOFAS/AGORA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/SISAL.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "ALPHA",
    nombre: "ALPHA",
    img: "../assets/imgs/SOFAS/ALPHA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/SISAL.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "ALTANO",
    nombre: "ALTANO",
    img: "../assets/imgs/SOFAS/ALTANO.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/SISAL.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "BARINE",
    nombre: "BARINE",
    img: "../assets/imgs/SOFAS/BARINE.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "BASSA",
    nombre: "BASSA",
    img: "../assets/imgs/SOFAS/BASSA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "BERTINA",
    nombre: "BERTINA",
    img: "../assets/imgs/SOFAS/BERTINA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "CORAL",
    nombre: "CORAL",
    img: "../assets/imgs/SOFAS/CORAL.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "DANA",
    nombre: "DANA",
    img: "../assets/imgs/SOFAS/DANA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "GAMMA",
    nombre: "GAMMA",
    img: "../assets/imgs/SOFAS/GAMMA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "GIANT",
    nombre: "GIANT",
    img: "../assets/imgs/SOFAS/GIANT.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "LINO",
    nombre: "LINO",
    img: "../assets/imgs/SOFAS/LINO.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "MEMPHIS",
    nombre: "MEMPHIS",
    img: "../assets/imgs/SOFAS/MEMPHIS.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "MISTRAL",
    nombre: "MISTRAL",
    img: "../assets/imgs/SOFAS/MISTRAL.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "NADIR",
    nombre: "NADIR",
    img: "../assets/imgs/SOFAS/NADIR.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "PLATEA",
    nombre: "PLATEA",
    img: "../assets/imgs/SOFAS/PLATEA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "SIGMA",
    nombre: "SIGMA",
    img: "../assets/imgs/SOFAS/SIGMA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "SIROCCO ECO",
    nombre: "SIROCCO ECO",
    img: "../assets/imgs/SOFAS/SIROCCOECO.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "SISAL",
    nombre: "SISAL",
    img: "../assets/imgs/SOFAS/SISAL.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "TUCSON",
    nombre: "TUCSON",
    img: "../assets/imgs/SOFAS/TUCSON.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "TUNDRA",
    nombre: "TUNDRA",
    img: "../assets/imgs/SOFAS/TUNDRA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "YUTE",
    nombre: "YUTE",
    img: "../assets/imgs/SOFAS/YUTE.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "ZENITH",
    nombre: "ZENITH",
    img: "../assets/imgs/SOFAS/ZENITH.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
  {
    id: "ZONDA",
    nombre: "ZONDA",
    img: "../assets/imgs/SOFAS/ZONDA.jpg",
    link: "../pages/product.html",
    categoria: "sofa",
    bg: "../assets/imgs/GENERAL/bgproducto.jpg",
    heroimg: "../assets/imgs/GENERAL/AGORAHERO.jpg",
    text: "Ágora es un sistema modular de infinitas posibilidades. Elige uno de sus dos respaldos (cojín articulado o cojín tradicional) y configura sus módulos poniendo el foco en el descanso hecho a tu medida.",
    img1: "../assets/imgs/GENERAL/AGORAFOTOS.png",
    img2: "../assets/imgs/GENERAL/AGORAFOTOS2.png",
    img3: "../assets/imgs/GENERAL/AGORAFOTOS3.png",
  },
];

const mobiliarios = [
  {
    id: "CALA",
    nombre: "CALA",
    img: "../assets/imgs/MOBILIARIO/CALAMESA.jpg",
    link: "../pages/product.html",
    categoria: "mobiliario",
  },
  {
    id: "REMO",
    nombre: "REMO",
    img: "../assets/imgs/MOBILIARIO/REMOMESA.jpg",
    link: "../pages/product.html",
    categoria: "mobiliario",
  },
  {
    id: "ISLA",
    nombre: "ISLA",
    img: "../assets/imgs/MOBILIARIO/ISLAMESA.jpg",
    link: "../pages/product.html",
    categoria: "mobiliario",
  },
];

const butacas = [
  {
    id: "ARES",
    nombre: "ARES",
    img: "../assets/imgs/BUTACAS/ARES.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "BRUMA",
    nombre: "BRUMA",
    img: "../assets/imgs/BUTACAS/BRUMA.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "CORAL",
    nombre: "CORAL",
    img: "../assets/imgs/BUTACAS/CORAL.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "CORALINA",
    nombre: "CORALINA",
    img: "../assets/imgs/BUTACAS/CORALINA.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "CRONO",
    nombre: "CRONO",
    img: "../assets/imgs/BUTACAS/CRONO.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "DANA",
    nombre: "DANA",
    img: "../assets/imgs/BUTACAS/DANA.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "EROS",
    nombre: "EROS",
    img: "../assets/imgs/BUTACAS/EROS.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "OMEGA",
    nombre: "OMEGA",
    img: "../assets/imgs/BUTACAS/OMEGA.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "DINO",
    nombre: "DINO",
    img: "../assets/imgs/BUTACAS/DINO.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "TASSOS",
    nombre: "TASSOS",
    img: "../assets/imgs/BUTACAS/TASSOS.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
  {
    id: "TITA",
    nombre: "TITA",
    img: "../assets/imgs/BUTACAS/TITA.jpg",
    link: "../pages/product.html",
    categoria: "butacas",
  },
];
